---
# User
server_data_dir_user: "{{ gv_local_wg_user }}"
server_data_dir_group: "{{ gv_local_wg_group }}"

# Container stack
container_data_root: "{{ gv_container_data_root }}"
management_container_stack_location: "{{ gv_local_wg_user_home }}/.container-stack-management"

docker_network_name: "{{ gv_docker_network_name }}"

# Portainer
portainer_config_path: "{{ container_data_root }}/portainer/config"
